# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'set_tmp.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
#!/usr/bin/python
# -*- coding: utf-8 -*-

import os
import json
import shutil
from PyQt5 import QtCore, QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QFileDialog, QWidget, QMessageBox, QApplication

class Ui_set(QWidget):
    def setupUi(self, set):
        # 启用高 DPI 支持
        QApplication.setAttribute(Qt.AA_EnableHighDpiScaling, True)
        QApplication.setAttribute(Qt.AA_UseHighDpiPixmaps, True)
        os.environ["QT_AUTO_SCREEN_SCALE_FACTOR"] = "1"
        set.setObjectName("set")
        set.resize(554, 620)
        self.textEdit = QtWidgets.QTextEdit(set)
        self.textEdit.setGeometry(QtCore.QRect(150, 410, 351, 111))
        self.textEdit.setObjectName("textEdit")

        self.textEdit_pinlv = QtWidgets.QTextEdit(set)
        self.textEdit_pinlv.setGeometry(QtCore.QRect(150, 570, 50, 30))
        self.textEdit_pinlv.setObjectName("textEdit_pinlv")

        self.textEdit_tuisong = QtWidgets.QTextEdit(set)
        self.textEdit_tuisong.setGeometry(QtCore.QRect(150, 530, 351, 30))
        self.textEdit_tuisong.setObjectName("textEdit_tuisong")

        self.label = QtWidgets.QLabel(set)
        self.label.setGeometry(QtCore.QRect(60, 440, 72, 15))
        self.label.setObjectName("label")

        self.label_pinlv = QtWidgets.QLabel(set)
        self.label_pinlv.setGeometry(QtCore.QRect(50, 580, 90, 15))
        self.label_pinlv.setObjectName("label_pinlv")

        self.label_tuisong = QtWidgets.QLabel(set)
        self.label_tuisong.setGeometry(QtCore.QRect(90, 540, 90, 15))
        self.label_tuisong.setObjectName("label_tuisong")

        self.comboBox = QtWidgets.QComboBox(set)
        self.comboBox.setGeometry(QtCore.QRect(10, 60, 121, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_2 = QtWidgets.QLabel(set)
        self.label_2.setGeometry(QtCore.QRect(30, 20, 91, 51))
        self.label_2.setObjectName("label_2")
        self.textEdit_2 = QtWidgets.QTextEdit(set)
        self.textEdit_2.setGeometry(QtCore.QRect(150, 40, 351, 51))
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_3 = QtWidgets.QTextEdit(set)
        self.textEdit_3.setGeometry(QtCore.QRect(149, 310, 351, 81))
        self.textEdit_3.setObjectName("textEdit_3")
        self.label_3 = QtWidgets.QLabel(set)
        self.label_3.setGeometry(QtCore.QRect(40, 330, 101, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(set)
        self.label_4.setGeometry(QtCore.QRect(30, 120, 91, 31))
        self.label_4.setObjectName("label_4")
        self.comboBox_2 = QtWidgets.QComboBox(set)
        self.comboBox_2.setGeometry(QtCore.QRect(10, 150, 121, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.textEdit_4 = QtWidgets.QTextEdit(set)
        self.textEdit_4.setGeometry(QtCore.QRect(150, 106, 351, 141))
        self.textEdit_4.setObjectName("textEdit_4")
        self.pushButton = QtWidgets.QPushButton(set)
        self.pushButton.setGeometry(QtCore.QRect(310, 260, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(set)
        self.pushButton_2.setGeometry(QtCore.QRect(410, 260, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(set)
        self.pushButton_3.setGeometry(QtCore.QRect(410, 590, 93, 28))
        self.pushButton_3.setObjectName("pushButton_3")

        # data
        self.renshe = ""
        self.moduel = ""
        self.jiankong_word = ""
        self.zhishi = ""
        self.retranslateUi(set)
        QtCore.QMetaObject.connectSlotsByName(set)

    def select_file(self):
        try:
            # 弹出文件选择对话框
            print("hello")
            file_path, _ = QFileDialog.getOpenFileName(
                self,  # 父窗口
                "选择文件",  # 对话框标题
                "",  # 初始目录（空表示默认目录）
                "所有文件 (*);;文本文件 (*.txt);;图片文件 (*.png *.jpg)"  # 文件过滤器
            )

            # 如果用户选择了文件（未点击取消）
            print(file_path)
            _translate = QtCore.QCoreApplication.translate
            if file_path:
                file_name = file_path.split("/")[-1]  # 从路径中提取文件名
                print(f"文件名: {file_name}")
                print(f"绝对路径hhhhhhhhhhh: {file_path}")
                # 复制文件（shutil.copy2 会保留元数据）
                shutil.copy2(file_path, ".\\zhishiku")
                self.zhishi[file_name] = ".\\zhishiku\\" + file_name
                self.comboBox_2.addItem("")
                self.comboBox_2.setItemText(self.comboBox_2.count()-1, _translate("wechat_ai", file_name))
                self.on_zhishiku_changed()
                self.updata_innerData()
        except Exception as ex:
            QMessageBox.warning(self, '警告', '新增文件失败，请截图黑色框给开发人员进行排查!!!', QMessageBox.Ok)
            print("新增文件失败，请截图黑色框给开发人员进行排查!!!")
            print(ex)
            pass


    def moduel_change(self):
        self.textEdit_2.setText(self.moduel[self.comboBox.currentText()])

    def updata_innerData(self):
        try:
            with open("config.json", 'r', encoding="gbk") as r:
                result_map = json.loads(r.read())
        except Exception:
            with open("config.json", 'r', encoding="utf-8") as r:
                result_map = json.loads(r.read())
        result_map['renshe'] = self.textEdit.toPlainText()
        result_map['jiankong_list'] = self.textEdit_3.toPlainText()
        result_map['moduel'] = self.moduel
        result_map['zhishi'] = self.zhishi
        result_map = json.dumps(result_map, indent=4,
                                sort_keys=True,
                                separators=(",", ": "))
        with open(self.zhishi[self.comboBox_2.currentText()], 'w', encoding='gbk') as w:
            w.write(self.textEdit_4.toPlainText())

        with open("config.json", 'w') as w:
            w.write(result_map)

    def updata_data(self):
        reply = QMessageBox.question(
            self,
            "确认操作",
            "确认要更新吗？",
            QMessageBox.Yes | QMessageBox.No,  # 按钮组合
            QMessageBox.No  # 默认选中按钮
        )
        if reply == QMessageBox.No:
            return

        with open("config.json", 'r', encoding="gbk") as r:
            result_map = json.loads(r.read())
        result_map['renshe'] = self.textEdit.toPlainText()
        result_map['jiankong_list'] = self.textEdit_3.toPlainText()
        result_map['moduel'] = self.moduel
        result_map['zhishi'] = self.zhishi
        result_map['pinlv'] = self.textEdit_pinlv.toPlainText()
        result_map['tuisong'] = self.textEdit_tuisong.toPlainText()

        result_map = json.dumps(result_map,indent=4,
                sort_keys=True,
                separators=(",", ": "))
        try:
            with open(self.zhishi[self.comboBox_2.currentText()], 'w', encoding='gbk') as w:
                w.write(self.textEdit_4.toPlainText())
        except Exception:
            with open(self.zhishi[self.comboBox_2.currentText()], 'w', encoding='utf-8') as w:
                w.write(self.textEdit_4.toPlainText())

        with open("config.json", 'w') as w:
            w.write(result_map)
        self.main.reUpdateData()

    def on_text_changed(self):
        self.moduel[self.comboBox.currentText()] = self.textEdit_2.toPlainText()

    def on_zhishiku_changed(self):
        try:
            with open(self.zhishi[self.comboBox_2.currentText()], 'r', encoding='gbk') as r:
                self.textEdit_4.setText(r.read())
        except Exception:
            try:
                with open(self.zhishi[self.comboBox_2.currentText()], 'r', encoding='utf-8') as r:
                    self.textEdit_4.setText(r.read())
            except Exception as ex:
                pass


    def delete_zhishi(self):
        # 弹出文件选择对话框
        print("delete")
        reply = QMessageBox.question(
            self,
            "确认操作",
            "确认要删除吗？",
            QMessageBox.Yes | QMessageBox.No,  # 按钮组合
            QMessageBox.No  # 默认选中按钮
        )
        if reply == QMessageBox.No:
            return

        try:
            # 删除实际文件
            real_path = ".\\zhishiku\\" + self.comboBox_2.currentText()
            os.remove(real_path)
        except Exception as ex:
            print(ex)

        try:
            with open("config.json", 'r', encoding="gbk") as r:
                data_map = json.loads(r.read())
            del data_map['zhishi'][self.comboBox_2.currentText()]
            with open("config.json", 'w', encoding="gbk") as w:
                w.write(json.dumps(data_map))
            with open("config.json", 'r', encoding="gbk") as r:
                data_map = json.loads(r.read())
            self.moduel = data_map["moduel"]
            self.jiankong_word = data_map['jiankong_list']
            self.renshe = data_map['renshe']
            self.zhishi = data_map['zhishi']
            file_names = list(self.zhishi.keys())

            _translate = QtCore.QCoreApplication.translate
            self.comboBox_2.clear()
            # 监控列表
            for i in range(len(file_names)):
                self.comboBox_2.addItem("")
                self.comboBox_2.setItemText(i, _translate("wechat_ai", str(file_names[i])))
            # 设置知识库
            self.comboBox_2.setCurrentIndex(0)
            self.comboBox_2.currentTextChanged.connect(self.on_zhishiku_changed)
            if len(file_names) > 0:
                self.on_zhishiku_changed()
        except Exception as ex:
            print(ex)

    def retranslateUi(self, set):
        _translate = QtCore.QCoreApplication.translate
        set.setWindowTitle(_translate("set", "设置"))
        self.label.setText(_translate("set", "默认人设"))

        self.label_tuisong.setText(_translate("set", "推送人"))
        self.label_pinlv.setText(_translate("set", "回复频率(秒)"))
        self.comboBox.setItemText(0, _translate("set", "deepseek-r1"))
        self.comboBox.setItemText(1, _translate("set", "doubao api"))
        self.comboBox.setItemText(2, _translate("set", "doubao app"))
        self.comboBox.setItemText(3, _translate("set", "coze"))
        self.comboBox.setCurrentIndex(0)
        self.comboBox.currentTextChanged.connect(self.moduel_change)

        self.label_2.setText(_translate("set", "api key设置"))
        self.label_3.setText(_translate("set", "默认回复列表"))
        self.label_4.setText(_translate("set", "知识库文件"))
        self.pushButton.setText(_translate("set", "新增"))
        self.pushButton.clicked.connect(self.select_file)

        # 连接信号：当文本变化时触发槽函数
        self.textEdit_2.textChanged.connect(self.on_text_changed)

        self.pushButton_2.setText(_translate("set", "删除"))
        self.pushButton_3.setText(_translate("set", "更新应用"))

        self.pushButton_2.clicked.connect(self.delete_zhishi)
        self.pushButton_3.clicked.connect(self.updata_data)

        with open("config.json", 'r', encoding="gbk") as r:
            data_map = json.loads(r.read())
        self.moduel = data_map["moduel"]
        self.jiankong_word = data_map['jiankong_list']
        self.renshe = data_map['renshe']
        self.zhishi = data_map['zhishi']
        self.pinlv = str(data_map['pinlv'])
        self.tuisong = data_map['tuisong']
        file_names = list(self.zhishi.keys())

        # 人设
        self.textEdit.setText(self.renshe)
        # 模型
        self.textEdit_2.setText(self.moduel[self.comboBox.currentText()])
        # 监控列表
        self.textEdit_3.setText(self.jiankong_word)
        # 频率
        self.textEdit_pinlv.setText(self.pinlv)
        # 推送人
        self.textEdit_tuisong.setText(self.tuisong)
        for i in range(len(file_names)):
            self.comboBox_2.addItem("")
            self.comboBox_2.setItemText(i, _translate("wechat_ai", str(file_names[i])))
        # 设置知识库
        self.comboBox_2.setCurrentIndex(0)
        self.comboBox_2.currentTextChanged.connect(self.on_zhishiku_changed)
        if len(file_names) > 0:
            self.on_zhishiku_changed()




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_set()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())