# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os
import time
import json
import keyboard
import jieba
from queue import Queue
from cozepy import COZE_CN_BASE_URL
from threading import Thread
from wxauto import WeChat
from openai import OpenAI
from picture_shibie import get_pic_word
from datetime import datetime, timedelta
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import (QMessageBox, QLabel, QVBoxLayout, QWidget,
                             QMainWindow, QDockWidget, QApplication, QGroupBox,
                             QHBoxLayout, QFrame, QDialog, QPushButton)
from PyQt5.QtCore import Qt, QTimer
from well import detect
from cozepy import Coze, TokenAuth, Message, ChatStatus, MessageContentType  # noqa


class PersonaEditorDialog(QDialog):
    """AI人设编辑弹窗"""

    def __init__(self, parent=None, initial_text=""):
        super().__init__(parent)
        self.setWindowTitle("编辑AI人设")
        self.resize(500, 400)
        self.initial_text = initial_text

        # 设置布局
        layout = QVBoxLayout(self)

        # 文本编辑区域
        self.text_edit = QtWidgets.QTextEdit()
        self.text_edit.setPlainText(initial_text)
        layout.addWidget(self.text_edit)

        # 按钮区域
        button_layout = QHBoxLayout()
        self.save_btn = QPushButton("保存")
        self.cancel_btn = QPushButton("取消")

        self.save_btn.clicked.connect(self.accept)
        self.cancel_btn.clicked.connect(self.reject)

        button_layout.addWidget(self.save_btn)
        button_layout.addWidget(self.cancel_btn)
        layout.addLayout(button_layout)

        # 应用样式
        self.setStyleSheet("""
            QDialog {
                font-family: "Microsoft YaHei", sans-serif;
                font-size: 14px;
                background-color: #f5f7fa;
            }
            QTextEdit {
                border: 1px solid #bdc3c7;
                border-radius: 4px;
                padding: 8px;
                background-color: white;
                font-size: 14px;
            }
            QPushButton {
                background-color: #3498db;
                color: white;
                border-radius: 5px;
                padding: 6px 12px;
                border: none;
                min-width: 80px;
            }
            QPushButton:hover {
                background-color: #2980b9;
            }
            QPushButton:pressed {
                background-color: #2471a3;
            }
        """)

    def get_text(self):
        """获取编辑后的文本"""
        return self.text_edit.toPlainText()


class Ui_wechat_ai(QWidget):
    # 定义样式常量
    STYLE_SHEET = """
    QWidget {
        font-family: "Microsoft YaHei", sans-serif;
        font-size: 14px;
        background-color: #f5f7fa;
    }
    QLabel#titleLabel {
        font-size: 18px;
        font-weight: bold;
        color: #2c3e50;
    }
    QLabel {
        color: #34495e;
    }
    QPushButton {
        background-color: #3498db;
        color: white;
        border-radius: 5px;
        padding: 6px 12px;
        border: none;
    }
    QPushButton:hover {
        background-color: #2980b9;
    }
    QPushButton:pressed {
        background-color: #2471a3;
    }
    QPushButton:disabled {
        background-color: #bdc3c7;
    }
    QComboBox, QTextEdit {
        border: 1px solid #bdc3c7;
        border-radius: 4px;
        padding: 5px;
        background-color: white;
    }
    QComboBox:hover, QTextEdit:hover {
        border-color: #3498db;
    }
    QGroupBox {
        border: 1px solid #bdc3c7;
        border-radius: 5px;
        margin-top: 10px;
        padding: 10px;
        background-color: white;
    }
    QGroupBox::title {
        subcontrol-origin: margin;
        left: 10px;
        color: #34495e;
        font-weight: bold;
    }
    QScrollArea {
        border: 1px solid #bdc3c7;
        border-radius: 5px;
        background-color: white;
    }
    QCheckBox {
        color: #34495e;
        spacing: 5px;
    }
    QToolButton {
        background-color: #2ecc71;
        color: white;
        border-radius: 4px;
    }
    QToolButton:hover {
        background-color: #27ae60;
    }
    """

    def showMessageBox(self):
        QMessageBox.information(self, 'Information', 'This is an information message.')  # 显示信息消息框

    def setupUi(self, wechat_ai):
        # 启用高 DPI 支持
        QApplication.setAttribute(Qt.AA_EnableHighDpiScaling, True)
        QApplication.setAttribute(Qt.AA_UseHighDpiPixmaps, True)
        os.environ["QT_AUTO_SCREEN_SCALE_FACTOR"] = "1"

        wechat_ai.setObjectName("wechat_ai")
        wechat_ai.resize(900, 600)  # 增大窗口尺寸
        wechat_ai.setStyleSheet(self.STYLE_SHEET)  # 应用样式表

        # 主布局
        main_layout = QHBoxLayout(wechat_ai)
        main_layout.setContentsMargins(15, 15, 15, 15)
        main_layout.setSpacing(15)

        # 左侧控制面板
        left_panel = QWidget()
        left_layout = QVBoxLayout(left_panel)
        left_layout.setSpacing(12)
        left_panel.setMinimumWidth(450)

        # 标题
        title_label = QLabel("微信AI客服助手")
        title_label.setObjectName("titleLabel")
        title_label.setAlignment(Qt.AlignCenter)
        left_layout.addWidget(title_label)

        # 第一组：基本设置（包含原基本设置和群聊设置）
        basic_group = QGroupBox("基本设置")
        basic_layout = QVBoxLayout(basic_group)
        basic_layout.setSpacing(10)

        # AI知识库设置
        kb_layout = QHBoxLayout()
        kb_label = QLabel("AI知识库:")
        kb_label.setFixedWidth(80)
        self.comboBox_2 = QtWidgets.QComboBox()
        self.comboBox_2.setObjectName("comboBox_2")
        self.toolButton = QtWidgets.QToolButton()
        self.toolButton.setText("设置")
        self.toolButton.setFixedWidth(50)
        kb_layout.addWidget(kb_label)
        kb_layout.addWidget(self.comboBox_2)
        kb_layout.addWidget(self.toolButton)
        basic_layout.addLayout(kb_layout)

        # 模型选择
        model_layout = QHBoxLayout()
        model_label = QLabel("模型选择:")
        model_label.setFixedWidth(80)
        self.comboBox = QtWidgets.QComboBox()
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("deepseek-r1")
        self.comboBox.addItem("doubao api")
        self.comboBox.addItem("doubao app")
        self.comboBox.addItem("coze")
        model_layout.addWidget(model_label)
        model_layout.addWidget(self.comboBox)
        basic_layout.addLayout(model_layout)

        # 复选框设置（基础功能）
        checkbox_layout = QHBoxLayout()
        checkbox_col1 = QVBoxLayout()
        checkbox_col2 = QVBoxLayout()

        self.checkbox_isUse = QtWidgets.QCheckBox("启用知识库")
        self.checkbox_isMatch = QtWidgets.QCheckBox("未匹配不回复")
        self.checkbox_newMatch = QtWidgets.QCheckBox("最近消息检索")
        self.checkbox_aite = QtWidgets.QCheckBox("艾特后回复")
        # 新增群聊相关复选框到基本设置
        self.checkbox_qunliao = QtWidgets.QCheckBox("回复群聊")
        self.checkbox_autojieshou = QtWidgets.QCheckBox("自动同意好友")

        checkbox_col1.addWidget(self.checkbox_isUse)
        checkbox_col1.addWidget(self.checkbox_isMatch)
        checkbox_col1.addWidget(self.checkbox_newMatch)
        checkbox_col2.addWidget(self.checkbox_aite)
        checkbox_col2.addWidget(self.checkbox_qunliao)  # 群聊设置添加到基本设置
        checkbox_col2.addWidget(self.checkbox_autojieshou)

        checkbox_layout.addLayout(checkbox_col1)
        checkbox_layout.addLayout(checkbox_col2)
        basic_layout.addLayout(checkbox_layout)

        left_layout.addWidget(basic_group)

        # 第二组：关键词设置
        keyword_group = QGroupBox("指定回复设置")
        keyword_layout = QVBoxLayout(keyword_group)

        keyword_top_layout = QHBoxLayout()
        self.checkbox_isAll = QtWidgets.QCheckBox("指定回复")
        keyword_top_layout.addWidget(self.checkbox_isAll)
        keyword_layout.addLayout(keyword_top_layout)

        self.textEdit = QtWidgets.QTextEdit()
        self.textEdit.setPlaceholderText("输入需要监控的关键词，多个关键词用逗号分隔")
        keyword_layout.addWidget(self.textEdit)

        left_layout.addWidget(keyword_group)

        # 第四组：AI人设设置
        persona_group = QGroupBox("AI人设设置")
        persona_layout = QVBoxLayout(persona_group)

        # 新增编辑按钮和文本区域布局
        persona_top_layout = QHBoxLayout()
        self.edit_persona_btn = QPushButton("编辑人设")
        self.edit_persona_btn.setFixedWidth(80)
        self.edit_persona_btn.clicked.connect(self.open_persona_editor)
        persona_top_layout.addWidget(self.edit_persona_btn)
        persona_top_layout.addStretch()  # 拉伸项，将按钮推到左侧
        persona_layout.addLayout(persona_top_layout)

        self.textEdit_2 = QtWidgets.QTextEdit()
        self.textEdit_2.setPlainText(
            "你是一个脾气很差的人，说话风格类似百度贴吧老哥，很没有耐心，说话非常有攻击力，允许你说脏话")
        self.textEdit_2.setReadOnly(True)  # 设置为只读，只能通过弹窗编辑
        persona_layout.addWidget(self.textEdit_2)

        left_layout.addWidget(persona_group)

        # 开始/停止按钮
        button_layout = QHBoxLayout()
        button_layout.setAlignment(Qt.AlignCenter)
        self.pushButton = QtWidgets.QPushButton("开始")
        self.pushButton.setMinimumHeight(40)
        self.pushButton.setStyleSheet("font-size: 16px; padding: 8px 24px;")
        button_layout.addWidget(self.pushButton)
        left_layout.addLayout(button_layout)

        # 右侧消息区域
        right_panel = QWidget()
        right_layout = QVBoxLayout(right_panel)

        # 消息区域标题
        chat_title = QLabel("聊天记录")
        chat_title.setObjectName("titleLabel")
        right_layout.addWidget(chat_title)

        # 滚动区域
        self.scrollArea = QtWidgets.QScrollArea()
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")

        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 299, 469))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")

        # 滚动区域的内容容器
        self.content_layout = QVBoxLayout(self.scrollAreaWidgetContents)
        self.content_layout.setAlignment(Qt.AlignTop)  # 内容从顶部开始排列
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        right_layout.addWidget(self.scrollArea)

        # 添加到主布局
        main_layout.addWidget(left_panel)
        main_layout.addWidget(right_panel, 1)  # 右侧区域可伸缩

        # 数据初始化
        self.renshe = ""
        self.moduel = ""
        self.jiankong_word = ""
        self.zhishi = ""
        self.data_queue = Queue()

        # 主线程定时轮询
        self.timer = QTimer()
        self.timer.timeout.connect(self.check_queue)
        self.timer.start(1000)

        self.flag = False
        try:
            windows = WeChat.get_windows()
            self.wx = WeChat(windows[0])
        except Exception:
            print("请先登录微信...")
            QMessageBox.warning(self, '提示', '请先登录微信后再启动本程序！', QMessageBox.Ok)
            raise

        self.deepseek_message = {}
        self.coze_message = []
        self.flag_sum = 1

        # 绑定信号与槽
        self.pushButton.clicked.connect(self.begin)

        # 加载配置数据
        self.retranslateUi(wechat_ai)
        QtCore.QMetaObject.connectSlotsByName(wechat_ai)

    def open_persona_editor(self):
        """打开AI人设编辑弹窗"""
        # 获取当前人设文本
        current_text = self.textEdit_2.toPlainText()

        # 创建并显示弹窗
        dialog = PersonaEditorDialog(self, current_text)
        if dialog.exec_() == QDialog.Accepted:
            # 如果用户点击了保存，更新文本
            new_text = dialog.get_text()
            self.textEdit_2.setPlainText(new_text)
            # 同时更新配置数据
            self.renshe = new_text

    def check_queue(self):
        while not self.data_queue.empty():
            data = self.data_queue.get()
            self.add_message(data)

    def add_message(self, text):
        """添加新消息，美化消息样式"""
        # 创建消息标签
        label = QLabel(text)
        label.setWordWrap(True)  # 允许自动换行
        label.setTextInteractionFlags(Qt.TextSelectableByMouse)  # 允许选择复制

        # 根据消息类型设置不同样式
        if "ai回复" in text:
            label.setStyleSheet("""
                background-color: #e3f2fd;
                border-radius: 8px;
                padding-left: 10px;
                margin: 5px 0px;
                width: 600px;
                border-left: 4px solid #2196f3;
            """)
        else:
            label.setStyleSheet("""
                background-color: #e8f5e9;
                border-radius: 8px;
                padding: 20px;
                margin: 5px 0px;
                width: 600px;
                border-left: 4px solid #4caf50;
            """)

        # 将消息添加到内容布局
        self.content_layout.addWidget(label)

        # 滚动到底部
        QTimer.singleShot(50, self.scroll_to_bottom)

    def scroll_to_bottom(self):
        """滚动到最底部"""
        scrollbar = self.scrollArea.verticalScrollBar()
        scrollbar.setValue(scrollbar.maximum())

    def reUpdateData(self):
        try:
            with open("config.json", encoding="utf-8") as r:
                data_map = json.loads(r.read())
        except Exception:
            with open("config.json", encoding="gbk") as r:
                data_map = json.loads(r.read())
        self.moduel = data_map["moduel"]
        self.jiankong_word = data_map['jiankong_list']
        self.renshe = data_map['renshe']
        self.zhishi = data_map['zhishi']
        self.pinlv = float(data_map['pinlv'])
        self.appId = data_map['AppID']
        self.SecretKey = data_map['SecretKey']
        self.tuisong = data_map['tuisong']

        self.textEdit.setText(self.jiankong_word)
        self.textEdit_2.setText(self.renshe)

        self.comboBox_2.clear()
        file_names = list(self.zhishi.keys())
        _translate = QtCore.QCoreApplication.translate
        for i in range(len(file_names)):
            self.comboBox_2.addItem("")
            self.comboBox_2.setItemText(i, _translate("wechat_ai", str(file_names[i])))

    def retranslateUi(self, wechat_ai):
        _translate = QtCore.QCoreApplication.translate
        wechat_ai.setWindowTitle(_translate("wechat_ai", "微信AI客服助手"))

        try:
            with open("config.json", encoding="utf-8") as r:
                data_map = json.loads(r.read())
        except Exception:
            with open("config.json", encoding="gbk") as r:
                data_map = json.loads(r.read())
        self.moduel = data_map["moduel"]
        self.jiankong_word = data_map['jiankong_list']
        self.renshe = data_map['renshe']
        self.zhishi = data_map['zhishi']
        self.pinlv = float(data_map['pinlv'])
        self.appId = data_map['AppID']
        self.SecretKey = data_map['SecretKey']
        self.tuisong = data_map['tuisong']

        self.textEdit.setText(self.jiankong_word)
        self.textEdit_2.setText(self.renshe)
        file_names = list(self.zhishi.keys())
        for i in range(len(file_names)):
            self.comboBox_2.addItem("")
            self.comboBox_2.setItemText(i, _translate("wechat_ai", str(file_names[i])))

    def fast_filter_from_csv(self, csv_string, question, top_k=10, content_column=None):
        # 1. 处理CSV字符串，分割成行和列
        lines = [line.strip() for line in csv_string.split('\n') if line.strip()]
        if not lines:
            return "CSV字符串中没有有效数据"

        # 提取表头和内容行
        header = lines[0].split(',')
        content_lines = lines[1:]

        # 2. 提取问题关键词（去停用词）
        stopwords = {'的', '是', '在', '吗', '呢', '我', '你', '有', '什么', '如何', '了', '这', '那', '和', '一个',
                     '什么'}
        question_words = jieba.lcut(question)
        keywords = [w for w in question_words if w not in stopwords and len(w) >= 1]

        if not keywords:
            # 若无关键词，返回前top_k条数据
            result = content_lines[:top_k]
            return "None"

        # 3. 确定用于匹配的列索引
        columns_to_check = []
        if content_column:
            # 查找指定列的索引
            if content_column in header:
                columns_to_check = [header.index(content_column)]
            else:
                return "None"
        else:
            # 检查所有列
            columns_to_check = list(range(len(header)))

        # 4. 计算每条记录的匹配分数并筛选
        scored_lines = []
        for line in content_lines:
            columns = line.split(',')
            score = 0
            content = columns[0]
            print("当前内容是））））））））））））））")
            print(content)
            for kw in keywords:
                if len(kw.strip()) == 0:
                    continue
                if kw in content:
                    score += 1
            if score > 0:
                scored_lines.append((-score, line))  # 用负分便于升序排序

        # 5. 排序并取前top_k条
        scored_lines.sort()  # 按分数降序排列（因为存的是负分）
        result_lines = [line for (score, line) in scored_lines[:top_k]]

        word = lines[0] + "\n"
        for result in result_lines:
            word += (result + "\n")

        if not result_lines:
            return "None"
        return word

    def ai_replay(self, user_name, renshe, msg_list, api_key, zhishi, model):
        zhishi = self.fast_filter_from_csv(zhishi, str(msg_list))

        print("当前匹配数据是））））））））））））")
        print(zhishi)

        # if "/" in zhishi and self.checkbox_isUse.isChecked():
        #     return zhishi.split("\n")[1].split(",")[1]


        if model == 'deepseek-r1':
            client = OpenAI(api_key=api_key, base_url="https://api.deepseek.com")
        elif model == 'doubao api':
            client = OpenAI(api_key=api_key.split("\n")[0], base_url="https://ark.cn-beijing.volces.com/api/v3")
        elif model == 'doubao app':
            client = OpenAI(api_key=api_key.split("\n")[0], base_url="https://ark.cn-beijing.volces.com/api/v3/bots")

        # 获取用户上下文
        if user_name not in self.deepseek_message:
            self.deepseek_message[user_name] = []

        if len(self.deepseek_message[user_name]) == 0:
            content = ""
            if not self.checkbox_isUse.isChecked():
                content = renshe
                self.deepseek_message[user_name].append({"role": "system", "content": content})
            else:
                print("test world ))))))))))))))")
                print(self.checkbox_isMatch)
                if self.checkbox_isMatch.isChecked():
                    self.deepseek_message[user_name].append(
                        {"role": "user", "content": "当询问的问题与知识库中的内容不匹配时则只回复wrong,"})
                    self.flag_sum = 2
                content = renshe + "；当询问文件或图片的时候直接回答文件名+逗号+True"
                self.deepseek_message[user_name].append(
                    {"role": "system", "content": content})

        # 当有新的匹配内容后再更新当前知识库内容
        if self.checkbox_isUse.isChecked() and zhishi is not None and zhishi != "" and zhishi != "None":
            content = renshe + "；当让你发文件或图片的时候直接回答文件名+逗号+True（多个文件顿号分隔，注意每个分隔都要带True）；并且你的回答需要基于以下csv文件内容: {zhishi}"
            self.deepseek_message[user_name][self.flag_sum - 1] = {"role": "system", "content": content}
            self.deepseek_message[user_name][self.flag_sum - 1]['content'] = \
                self.deepseek_message[user_name][self.flag_sum - 1]['content'].format(
                    zhishi=zhishi)

        for msg in msg_list:
            self.deepseek_message[user_name].append({"role": "user", "content": msg})

        if model == 'deepseek-r1':
            response = client.chat.completions.create(
                model="deepseek-chat",
                messages=self.deepseek_message[user_name],
                stream=False
            )
        elif model == 'doubao api':
            response = client.chat.completions.create(
                model=api_key.split("\n")[1],
                messages=self.deepseek_message[user_name],
                stream=False
            )
        elif model == 'doubao app':
            response = client.chat.completions.create(
                model=api_key.split("\n")[0],
                messages=self.deepseek_message[user_name],
                stream=False
            )

        reply = response.choices[-1].message.content

        if "wrong" in reply:
            # 假如是wrong则不加入
            self.deepseek_message[user_name] = self.deepseek_message[user_name][:-1]
        else:
            # 假如是图片，识别下图片内容后再存放到记录中
            if "jpg" in reply or "png" in reply:
                file_list = reply.split("、")
                for file in file_list:
                    word = get_pic_word(os.path.join('file', file.split(',')[0]), self.appId, self.SecretKey)
                    self.deepseek_message[user_name].append({"role": "assistant", "content": word})
            else:
                self.deepseek_message[user_name].append({"role": "assistant", "content": reply})

        # 保持上下文长度不超过5条消息
        if len(self.deepseek_message[user_name]) > 20:
            self.deepseek_message[user_name] = self.deepseek_message[user_name][:self.flag_sum] + self.deepseek_message[user_name][-10:]
            # self.deepseek_message[user_name] = []
            print("after clear)))))))))))))))))")
            print(self.deepseek_message[user_name])

        return reply

    def coze_replay(self, user_name, word, api_key):
        tmp_list = api_key.split('\n')
        api_key = tmp_list[0]
        bot_id = tmp_list[1]

        coze_api_token = api_key
        # The default access is api.coze.com, but if you need to access api.coze.cn,
        # please use base_url to configure the api endpoint to access
        coze_api_base = COZE_CN_BASE_URL

        from cozepy import Coze, TokenAuth, Message, ChatStatus, MessageContentType  # noqa

        # Init the Coze client through the access_token.
        coze = Coze(auth=TokenAuth(token=coze_api_token), base_url=coze_api_base)

        # Create a bot instance in Coze, copy the last number from the web link as the bot's ID.
        bot_id = bot_id
        # The user id identifies the identity of a user. Developers can use a custom business ID
        # or a random string.
        user_id = user_name

        # To simplify the call, the SDK provides a wrapped function to complete non-streaming chat,
        # polling, and obtaining the messages of the chat. Developers can use create_and_poll to
        # simplify the process.
        self.coze_message.append(Message.build_user_question_text(word))

        chat_poll = coze.chat.create_and_poll(
            bot_id=bot_id,
            user_id=user_id,
            additional_messages=self.coze_message
        )

        print("now the message is))))))))))))")
        print(chat_poll.messages[0].content)

        return chat_poll.messages[0].content

    def begin(self):
        moxing_type = self.comboBox.currentText()
        jianting_list = self.textEdit.toPlainText()
        renshe = self.textEdit_2.toPlainText()
        self.deepseek_message = {}
        self.flag_sum = 1

        def inner_jiankong():
            def on_esc_press(event):
                """按下ESC键时执行的回调函数"""
                if event.name == 'q':
                    self.flag = False
                    self.pushButton.setText("开始")
                    self.flag = False

            while True:
                # 设置回调函数，当ESC键被按下时调用on_esc_press函数
                keyboard.on_press(on_esc_press)
                if not self.flag:
                    print("is false, break))))))))))))))))")
                    break
                print("test))))))))))))))")
                print(self.checkbox_isAll.isChecked())
                if self.checkbox_isAll.isChecked() and self.textEdit.toPlainText() == "":
                    print("开始检测）））））））））））））")
                    try:
                        detect(moxing_type, renshe)
                    except Exception:
                        pass
                    continue
                try:
                    if self.checkbox_autojieshou.isChecked():
                        newfriends = self.wx.GetNewFriends()
                        for friend in newfriends:
                            friend.Accept(remark=friend.name, tags=["好友"])
                        self.wx._show()
                        self.wx.A_ChatIcon.DoubleClick()

                    time.sleep(2)
                    sessions = self.wx.GetSession()

                    if len(sessions) == 0:
                        try:
                            print("尝试重新获取窗口中01...")
                            windows = WeChat.get_windows()
                            self.wx = WeChat(windows[0])
                            print("获取窗口成功！！！")
                        except Exception:
                            print("获取窗口失败！！！")
                            pass
                    for session in sessions:
                        try:
                            print(session.name)
                            if (str(session.name) in jianting_list and self.checkbox_isAll.isChecked()) or not self.checkbox_isAll.isChecked():
                                # 只要还没回答就回答即可
                                # 获取当前时间
                                now = datetime.now()
                                current_time_str = now.strftime("%H:%M")
                                print("enter))))))))))))))")
                                print(session.content)
                                if session.content is None or session.content.strip() == "" or "订阅号" in session.name or "新闻" in session.name or "运动" in session.name or "微信" in session.name:
                                    print("跳过）））））））））））））")
                                    continue
                                # 将目标时间和当前时间转换为时间对象
                                try:
                                    target_time = datetime.strptime(session.time, "%H:%M")
                                except Exception:
                                    continue
                                current_time = datetime.strptime(current_time_str, "%H:%M")

                                # 计算时间差
                                time_difference = abs(target_time - current_time)
                                if (time_difference <= timedelta(minutes=5) and self.checkbox_newMatch.isChecked()) or (not self.checkbox_newMatch.isChecked() and session.isnew):
                                    if "：" in session.content and not self.checkbox_qunliao.isChecked():
                                        print("回复群聊未启用，跳过。。。")
                                        continue

                                    if (((self.deepseek_message.get(session.name) and
                                            len(self.deepseek_message[session.name]) > 0) and
                                            session.content == self.deepseek_message[session.name][-1]["content"]) and
                                            self.deepseek_message[session.name][-1]["role"] == "assistant"):
                                        print("旧消息，不回复。。。")
                                        continue

                                    self.wx.UiaAPI.SwitchToThisWindow()
                                    time.sleep(1)
                                    self.wx.ChatWith(who=session.name)
                                    msg = self.wx.GetAllMessage(savevoice=True)

                                    if len(msg) == 0:
                                        print("无消息，跳过....")
                                        continue
                                    msg = msg[-1]
                                    if msg.type != 'friend':
                                        print("非friend,跳过...")
                                        continue

                                    if "：" in session.content and self.checkbox_aite.isChecked() and '@' + self.wx.nickname not in msg.content:
                                        print('@' + self.wx.nickname)
                                        print(msg)
                                        print("当前未艾特，跳过...")
                                        continue

                                    # 循环判断当前是否还有新消息
                                    pre_content = msg.content
                                    while True:
                                        time.sleep(self.pinlv)
                                        cur_content = self.wx.GetAllMessage()[-1].content
                                        if cur_content != pre_content:
                                            print("当前聊天有新消息，继续扫描...")
                                            pre_content = cur_content
                                            continue
                                        else:
                                            print("扫描完成，退出...")
                                            break

                                    msgs = self.wx.GetAllMessage(savevoice=True)
                                    msgs.reverse()
                                    msg_list = []
                                    for msg in msgs:
                                        if "新消息" in msg.content:
                                            continue

                                        if msg.type == 'friend':
                                            msg_list.append(msg)
                                        else:
                                            break
                                    msg_list.reverse()

                                    print("当前消息内容）））））））））））", str(msg_list))
                                    result_list = []
                                    for msg in msg_list:
                                        if '[图片]' in msg.content:
                                            save_path = self.wx._download_pic(msg.control)
                                            word = get_pic_word(save_path, self.appId, self.SecretKey)
                                            result_list.append(word)
                                        elif '微信转账' in msg.content:
                                            self.wx.SendMsg(msg="好的 收到！", who=session.name)
                                            self.wx.SendMsg(msg="当前客户[{}]已成交，望知悉！".format(session.name), who=self.tuisong)
                                            return
                                        else:
                                            result_list.append(msg.content)

                                    print("最终整理后结果)))))))))))))))))", str(result_list))

                                    new_replay = ""
                                    zhishi = ""
                                    try:
                                        with open(self.zhishi[self.comboBox_2.currentText()], "r", encoding="gbk") as r:
                                            zhishi = r.read()
                                    except Exception:
                                        with open(self.zhishi[self.comboBox_2.currentText()], "r",
                                                  encoding="utf-8") as r:
                                            zhishi = r.read()

                                    if moxing_type == "deepseek-r1":
                                        new_replay = self.ai_replay(session.name, renshe, result_list,
                                                                    self.moduel["deepseek-r1"], zhishi, 'deepseek-r1')
                                    if moxing_type == "doubao api":
                                        new_replay = self.ai_replay(session.name, renshe, result_list,
                                                                    self.moduel["doubao api"], zhishi, "doubao api")
                                    if moxing_type == "doubao app":
                                        new_replay = self.ai_replay(session.name, renshe, result_list,
                                                                    self.moduel["doubao app"], zhishi, "doubao app")

                                    if moxing_type == "coze":
                                        new_replay = self.coze_replay(session.name, msg.content, self.moduel["coze"])

                                    self.data_queue.put(f"<font color='green'>{session.name}</font>：{msg.content}")
                                    self.data_queue.put(f"<font color='blue'>✅ 🤖ai回复</font>：{new_replay}\n")
                                    print("发送一条消息999））））））））））））））））")
                                    print(new_replay)
                                    if "wrong" in new_replay:
                                        print("消息不匹配，跳过...")
                                        continue
                                    if 'True' in new_replay:
                                        file_list = new_replay.split("、")
                                        for file in file_list:
                                            file_name = file.split(',')[0]
                                            print("send file)))))))))))))))))")
                                            print(os.path.join('file', file_name))
                                            self.wx.SendFiles(filepath=os.path.join('file', file_name))
                                    elif "/" in new_replay:
                                        message_list = new_replay.split("/")
                                        print("msg is ))))))))))))))))))))")
                                        print(message_list)
                                        for message in message_list:
                                            if message == "":
                                                continue
                                            if message.isdigit():
                                                self.wx.ChatWith("文件传输助手")
                                                msgs = self.wx.GetAllMessage()
                                                msgs[-int(message)].forward(session.name)
                                            else:
                                                self.wx.SendMsg(msg=message, who=session.name)
                                    else:
                                        self.wx.SendMsg(msg=new_replay, who=session.name)
                                else:
                                    print("time over))))))))))))")
                        except Exception as ex:
                            print("发送出错，", str(ex))
                            try:
                                print("尝试重新获取窗口中02...")
                                windows = WeChat.get_windows()
                                self.wx = WeChat(windows[0])
                                print("获取窗口成功！！！")
                            except Exception:
                                print("获取窗口失败！！！")
                                pass
                            continue
                    time.sleep(self.pinlv)
                except Exception as ex:
                    print("发送失败，", str(ex))
                    try:
                        print("尝试重新获取窗口中03...")
                        windows = WeChat.get_windows()
                        self.wx = WeChat(windows[0])
                        print("获取窗口成功！！！")
                    except Exception:
                        print("获取窗口失败！！！")
                        pass
                    continue

        self.flag = not self.flag
        if self.flag:
            self.pushButton.setText("停止")
            t1 = Thread(target=inner_jiankong)
            t1.start()
        else:
            self.pushButton.setText("开始")


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    wechat_ai = QtWidgets.QWidget()  # 创建窗口实例
    ui = Ui_wechat_ai()
    ui.setupUi(wechat_ai)  # 初始化界面
    wechat_ai.show()  # 显示窗口
    sys.exit(app.exec_())